SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `doc_agent` ADD `p_agent` INT NULL DEFAULT NULL COMMENT 'Подчинение другому агенту', ADD INDEX ( `p_agent` );
ALTER TABLE `doc_agent` ADD FOREIGN KEY ( `p_agent` ) REFERENCES `site`.`doc_agent` (`id` ) ON DELETE NO ACTION ON UPDATE NO ACTION ;

ALTER TABLE `doc_list` ADD `contract` INT NULL COMMENT 'Номер договора' AFTER `agent` ,ADD INDEX ( `contract` )

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

START TRANSACTION;
TRUNCATE `db_version`;
INSERT INTO `db_version` (`version`) VALUES (289);

COMMIT;